language: r
r:
  - 3.1
  - oldrel
  - release
  - devel
cache: packages
sudo: false
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("opposite", "print\\."))'
